### PR TITLE
Adding more tests and some other bug fixes.

### PR DESCRIPTION
**Pull request by hhslepicka**

### CODE REVIEW

**Comment by hhslepicka** [comment]
@arkilic, merge this! :bowtie: :revolving_hearts: :ear_of_rice:

**Comment by ghost** [comment]
@hhslepicka whoa! 89% coverage!

**Comment by hhslepicka** [comment]
👍  We need to do the same on amostra and also at the other services. With pytest-tornado it is much easier.

**Comment by ghost** [comment]
Yes, time is my concern. Not ease of use. As they get more mature, there is an absolute need for this stuff. Great job sir! 🎯 👍 🎉

**Pull request merged**
